package com.calix.bean;
// Generated 2019/10/26 �U�� 04:25:37 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Information generated by hbm2java
 */
public class Information implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6824256432198560522L;
	private Integer id;
	private String title;
	private String content;
	private Date publishtime;
	private Date deadlinetime;
	private String publishuser;

	public Information() {
	}

	public Information(String title, String content, Date publishtime, Date deadlinetime, String publishuser) {
		this.title = title;
		this.content = content;
		this.publishtime = publishtime;
		this.deadlinetime = deadlinetime;
		this.publishuser = publishuser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishtime() {
		return this.publishtime;
	}

	public void setPublishtime(Date publishtime) {
		this.publishtime = publishtime;
	}

	public Date getDeadlinetime() {
		return this.deadlinetime;
	}

	public void setDeadlinetime(Date deadlinetime) {
		this.deadlinetime = deadlinetime;
	}

	public String getPublishuser() {
		return this.publishuser;
	}

	public void setPublishuser(String publishuser) {
		this.publishuser = publishuser;
	}

	@Override
	public String toString() {
		return "Information [id=" + id + ", title=" + title + ", content=" + content + ", publishtime=" + publishtime
				+ ", deadlinetime=" + deadlinetime + ", publishuser=" + publishuser + "]";
	}

}
